services:
  postgres:
    image: postgres:latest
    deploy:
      resources:
        limits:
          memory: 16g
    container_name: slackr2-postgres
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - slackr2-network
    env_file:
      - ./.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: slackr2-backend
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_DB: ${DATABASE_NAME}
      NODE_ENV: ${NODE_ENV}
    networks:
      - slackr2-network
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: slackr2-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - slackr2-network
    env_file:
      - ./frontend/.env

networks:
  slackr2-network:
    driver: bridge

volumes:
  postgres-data:
